on:
  workflow_call:
    inputs:
      compose_files:
        description: 'Compose files'
        default: 'compose.yaml:compose.ci.yaml'
        required: false
        type: string
name: Build artifacts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: druidfi/stonehenge

      - name: Install and start Stonehenge
        run: make up

      - name: Setup Docker compose environment variables
        run: |
          echo "COMPOSE_FILE=${{ inputs.compose_files }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Start project
        run: make up

      - name: Build project
        run: docker compose exec app bash -c "composer install --no-interaction"

      - name: Setup drupal and save database dump
        run: |
          docker compose exec app bash -c "drush si -y && drush cr"
          docker compose exec app bash -c "drush si --existing-config -y"
          docker compose exec app bash -c "drush cr"
          docker compose exec app bash -c "drush cim -y"
          docker compose exec app bash -c "drush sql-dump --result-file=/app/latest.sql --extra-dump=--skip-ssl"

      - name: Upload latest database dump
        uses: actions/upload-artifact@v4
        with:
          name: latest.sql
          path: latest.sql
          retention-days: 10
