on:
  workflow_call:
    inputs:
      domain:
        description: 'The domain'
        required: true
        type: string
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Install wget2
        run: sudo apt-get update && sudo apt-get install wget2

      - name: Mirror the website content
        run: |
          # --ignore-tags: Ignore all assets like images, CSS and JS.
          # --follow-tags: Only follow <a> links.
          wget2 --mirror \
            --convert-links \
            --adjust-extension \
            -P contents \
            -e robots=off \
            --ignore-tags=img,link,script,picture,source,meta \
            --follow-tags=a \
            ${{ inputs.domain }}

      - name: Upload the mirrored website content
        uses: actions/upload-artifact@v6
        with:
          name: scraping-tool-results
          path: contents
          retention-days: 10
